### ISSUE TITLE
What should we name all the things we add

### ISSUE THREAD

**Issue by MarcusElg** [JoseluGames/MinecraftModdingDoneRight#16]
I think that we need some good system for all blocks/item we are adding. I think evertyhing should be called example_block or example_item or example_creative_tab. tutorial_item would also work but I think it's important that everything is named in the same way it makes everything look much cleaner.

**Comment by JoseluGames** [comment]
Yes, and also we need to make somekind of "preset" for the code arrangement

**Comment by MarcusElg** [comment]
So you agree that everything should be named for example example_block?
