### ISSUE TITLE
Checking side in initialisation while a client proxy exists.

### ISSUE THREAD

**Issue by Kethas** [JoseluGames/MinecraftModdingDoneRight#2]
There is no need to check for a side in an initialisation method if a client proxy exists. Also, `ClientProxy` and `ServerProxy` should extend a `CommonProxy` class. You can also pass the initialisation event objects to the proxy so it can use configuration files and whatnot.

Example:
`CommonProxy.java`

```
public void preInit(FMLPreInitializationEvent preInit){}

public void init(FMLInitializationEvent init){}

public void postInit(FMLPostInitializationEvent postInit){}
```

`ServerProxy.java` and `ClientProxy.java` (`extends CommonProxy`)

```
@Override
public void preInit(FMLPreInitializationEvent preInit){
    doStuff();
    super.preInit(preInit);
    beforeAndAfterCommonProxy(preInit);
}
@Override
public void init(FMLInitializationEvent init){
    registerBlocks();
    super.init(init);
}
@Override
public void postInit(FMLPostInitializationEvent postInit){
    super.postInit(postInit);
}
```

There is no need to check for side in a proxy since it will create the object depending on the side. If on client, a client proxy will be created, which has client-side functions and vice-versa.

**Comment by JoseluGames** [comment]
So I have to change this part of the Main class:

``` Java
    @EventHandler
    public static void Init(FMLInitializationEvent event){
        if(event.getSide() == Side.CLIENT){
            MMDRBlock.registerBlock();
            MMDRItem.registerItem();
        }

        proxy.Init();
    }
```

to this:

``` Java
    @EventHandler
    public static void Init(FMLInitializationEvent event){
        MMDRBlock.registerBlock();
        MMDRItem.registerItem();

        proxy.Init();
    }
```

and the proxys as you said right?

**Comment by JoseluGames** [comment]
And change the proxy function to 

``` Java
proxy.Init(event);
```

**Comment by Kethas** [comment]
The functions in you main class should only contain `proxy.init(event)` (or `preinit`, `postInit`...). All side neutral actions can be carried out in `CommonProxy`.

**Comment by JoseluGames** [comment]
Ok, now I get it, fast reading :sweat_smile:

**Comment by Kethas** [comment]
Glad to help :laughing:

**Comment by JoseluGames** [comment]
Giving me an error (Probably some silly error from my part hahaha)

```
Caused by: net.minecraftforge.fml.common.LoaderException: Attempted to load a proxy type com.jlgm.mmdr.main.ClientProxy into com.jlgm.mmdr.main.MMDRMain.proxy, but the types don't match
```

**Comment by JoseluGames** [comment]
If you want I can commit and push it so you can look at the code

**Comment by Kethas** [comment]
Yeah sure.

**Comment by JoseluGames** [comment]
Pushed!

**Comment by Kethas** [comment]
Thanks.

**Comment by Kethas** [comment]
Change the type of `MMDRMain.proxy` from `ServerProxy` to `CommonProxy`.

**Comment by JoseluGames** [comment]
Fixed and working!! Thank you very much :smile:

**Comment by Kethas** [comment]
No problem.
