### ISSUE TITLE
Only Registering Block in Client?

### ISSUE THREAD

**Issue by Ugdhar** [JoseluGames/MinecraftModdingDoneRight#4]
I'm just wondering, but it looks like the block is only being registered by the client. Wouldn't this cause the mod to not work if it were deployed on a server?

ClientProxy#init calls MMDRBlock.registerBlock(); which makes sense for the renderer, but I'm not sure if it's right for the block/item registration.

Sorry I didn't post the appplicable code, still figuring out how github issue reporting works :)

**Comment by JoseluGames** [comment]
Probably true, I'll fix it when I'm home
